---
- block:
    - name: Add Oracle apt public key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: Add Oracle repository
      apt_repository:
        repo: "deb https://download.virtualbox.org/virtualbox/debian {{ansible_lsb.codename}} contrib"
    - name: Install virtualbox
      apt: update_cache=yes pkg=virtualbox-5.2
  become: true
