---
- hosts: all
  become: true
  pre_tasks:
    - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
      raw: apt-get install python-minimal aptitude -y
      become: true
      become_user: root
      become_method: sudo
  tasks:
    - name: apt upgrade
      apt: update_cache=yes upgrade=yes cache_valid_time=3600
    - name: Remove old versions of Docker
      apt: state=absent pkg={{item}}
      with_items:
        - docker
        - docker-engine
        - docker.io
    - name: Install prerequisite packages for Docker
      apt: state=present pkg={{item}}
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add the Docker key using apt_key to prevent apt/apt-get warnings
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F76221572C52609D
    - debug: msg="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    - name: Add the Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install docker-ce
      apt: pkg=docker-ce
