---
- hosts: all
  pre_tasks:
    - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
      raw: apt-get install python-minimal aptitude -y
      become: true
  roles:
    - docker-ce
    - virtualbox
    - vagrant
    - kubectl
    - minikube
    - vscode
