---
apiVersion: v1
kind: Service
metadata:
  name: hello-phoenix
  labels:
    app: hello
spec:
  type: NodePort
  ports:
    - port: 4000
  selector:
    app: hello
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-phoenix
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-phoenix
        image: hello-phoenix:0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: PHOENIX_SECRET_KEY_BASE
            value: "vX67+AxbdkGYxQRbyk9FaRdWevtlxGIMldj259G2xISJYYN0L0nYZ40sjxrhFEWY"
          - name: PHOENIX_POSTGRES_HOSTNAME
            value: postgres
          - name: PHOENIX_POSTGRES_USER
            value: postgres
          - name: PHOENIX_POSTGRES_PASSWORD
            value: secret
          - name: PHOENIX_POSTGRES_DATABASE
            value: postgres
        ports:
          - containerPort: 4000
