---
- block:
    - name: apt upgrade
      apt: update_cache=yes upgrade=yes cache_valid_time=3600
    - name: Remove old versions of Docker
      apt: state=absent pkg={{item}}
      with_items:
        - docker
        - docker-engine
        - docker.io
    - name: Install prerequisite packages for Docker
      apt: state=present pkg={{item}}
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-pip
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add the Docker key using apt_key to prevent apt/apt-get warnings
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F76221572C52609D
    - name: Add the Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install docker-ce
      apt: pkg=docker-ce
    - name: Ensure docker group exists
      group: name=docker state=present
    - name: Add current user to docker group
      user: name="{{ansible_user_id}}" groups=docker append=yes
    - name: Ensure docker-py Python library is available
      pip: name=docker-py
  become: true
- name: Pre-pull Docker images used in exercises
  docker_image: name={{item}}
  with_items:
    - "mysql:8.0"
    - "mysql"
    - "mariadb:10.3"
    - "mariadb"
    - "alpine:3.7"
    - "alpine"
    - "aisrael/memory_eater:0.1"
    - "aisrael/memory_eater"
    - "aisrael/tweeter"
    - "wordpress:4.9.5"
