---
- name: Fetch minikube
  get_url:
    url: "https://github.com/kubernetes/minikube/releases/download/{{minikube.version}}/minikube-linux-amd64"
    dest: "/usr/local/bin/minikube"
    mode: "a+x"
    checksum: "{{minikube.checksum}}"
  become: true
